name: Deploy Multiple AWS Lambdas

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda:
          - name: inferLLM
            function_name: YourLambdaOneFunctionName
            source_path: lambda_src/inferLLM/

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Package the specific Lambda
      - name: Package ${{ matrix.lambda.name }}
        run: |
          mkdir package
          cp -r ${{ matrix.lambda.source_path }}/* package/
          cd package
          zip -r ${{ matrix.lambda.name }}.zip .
        shell: bash

      # Step 3: Deploy the Lambda function
      - name: Deploy ${{ matrix.lambda.name }}
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda.function_name }} \
            --zip-file fileb://${{ matrix.lambda.name }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}